// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgnmypbYfsKLBd6d_k7jLukcYjyXbKKJQ',
    appId: '1:806612693237:web:972cdba29945ee1cac95bc',
    messagingSenderId: '806612693237',
    projectId: 'myntra-clone-c27cf',
    authDomain: 'myntra-clone-c27cf.firebaseapp.com',
    storageBucket: 'myntra-clone-c27cf.appspot.com',
    measurementId: 'G-GJDVSG8JPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv7QAthgafOtVj2ZnUDdv2qjOmr38hwHw',
    appId: '1:806612693237:android:fb67ffc208ff8fbcac95bc',
    messagingSenderId: '806612693237',
    projectId: 'myntra-clone-c27cf',
    storageBucket: 'myntra-clone-c27cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCayQui2wBfEviNeFov0MLP8h9LrEmFAlE',
    appId: '1:806612693237:ios:6c8e09222e43c4bcac95bc',
    messagingSenderId: '806612693237',
    projectId: 'myntra-clone-c27cf',
    storageBucket: 'myntra-clone-c27cf.appspot.com',
    androidClientId: '806612693237-itqpo6vmbb1ac0jq9980rjjuo0dmls9b.apps.googleusercontent.com',
    iosClientId: '806612693237-rssl6pr84jl3abrq5cvectf9srm8ti4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.myntra',
  );
}
